version: "3"

services: 
  product-service:
    build: "./microservices"
    command: npm run start:product
    environment:
      PORT: 5001
    ports:
      - 5001:5001

  meta-service:
    build: "./microservices"
    command: npm run start:meta
    environment:
      PORT: 5003
    ports:
      - 5003:5003
    

  user-content-service:
    build: "./microservices"
    command: npm run start:ugc
    environment:
      PORT: 5002
    ports:
      - 5002:5002
    volumes: 
      - ./microservices:/opt/app

  pdp-service:
    build: "./microservices"
    command: npm run start:pdp
    environment:
      PORT: 5004
      PRODUCT_HOST: http://product-service:5001
      META_HOST: http://meta-service:5003
      UGC_HOST: http://user-content-service:5002
    ports:
      - 5004:5004
    
  
  react-app:
    build: "./pdp-react-app"
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    


  